eLConsultation/Controllers/CompanyController.cs
using eLConsultation.Data;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

using System.Linq;

using System.Web.Mvc;


namespace eLConsultation.Controllers
{
    [Authorize(Roles = "administrator, writer")]
    public class CompanyController : Controller
    {
        CompanyService service;

        public CompanyController()
        {
            service = new CompanyService();
        }

        [Authorize(Roles = "administrator, writer, reader")]
        public JsonResult CompanyList()
        {
            return Json(service.GetCompanys(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "administrator, writer, reader")]
        public ActionResult FilterCompanys([DataSourceRequest]DataSourceRequest request, string companyName)
        {
            ViewBag.ScreenWidth = Request.Browser.ScreenPixelsWidth;
            var companySearch = new CompanySearch { CompanyName = companyName};
            Session["companySearch"] = companySearch;
            DataSourceResult result = service.SearchCompanySetItems(companySearch).ToDataSourceResult(request);
            return Json(result);
        }

        [Authorize(Roles = "administrator, writer, reader")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "administrator, writer, reader")]
        public ActionResult CompanySelect([DataSourceRequest] DataSourceRequest request)
        {
            return Json(service.GetCompanys().ToDataSourceResult(request));
        }

        [Authorize(Roles = "administrator, writer, reader")]
        public ActionResult GetTypeConsultationsByCompanyID([DataSourceRequest] DataSourceRequest request, int companyID)
        {
            DataSourceResult result = service.GetTypeConsultationsByCompanyID(companyID).ToDataSourceResult(request);
            return Json(result);
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CompanyCreate([DataSourceRequest] DataSourceRequest request, CompanyItem companyItem)
        {
            if (companyItem != null && ModelState.IsValid)
            {
                service.CreateCompany(companyItem);
            }
            return Json(new[] { companyItem }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CompanyUpdate([DataSourceRequest] DataSourceRequest request, CompanyItem companyItem)
        {
            if (companyItem != null && ModelState.IsValid)
            {
                service.UpdateCompany(companyItem);
            }
            return Json(new[] { companyItem }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CompanyDelete([DataSourceRequest] DataSourceRequest request, CompanyItem companyItem)
        {
            if (companyItem != null)
            {
                service.DeleteCompany(companyItem);
            }
            return Json(new[] { companyItem }.ToDataSourceResult(request, ModelState));
        }
    }
}

eLConsultation/Controllers/GenderController.cs
using eLConsultation.Data;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

using System.Linq;

using System.Web.Mvc;


namespace eLConsultation.Controllers
{
    [Authorize(Roles = "administrator")]
    public class GenderController : Controller
    {
        GenderService service;

        public GenderController()
        {
            service = new GenderService();
        }

        public JsonResult GenderList()
        {
            return Json(service.GetGenders(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GenderSelect([DataSourceRequest] DataSourceRequest request)
        {
            return Json(service.GetGenders().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GenderCreate([DataSourceRequest] DataSourceRequest request, GenderItem genderItem)
        {
            if (genderItem != null && ModelState.IsValid)
            {
                service.CreateGender(genderItem);
            }
            return Json(new[] { genderItem }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GenderUpdate([DataSourceRequest] DataSourceRequest request, GenderItem genderItem)
        {
            if (genderItem != null && ModelState.IsValid)
            {
                service.UpdateGender(genderItem);
            }
            return Json(new[] { genderItem }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GenderDelete([DataSourceRequest] DataSourceRequest request, GenderItem genderItem)
        {
            if (genderItem != null)
            {
                service.DeleteGender(genderItem);
            }
            return Json(new[] { genderItem }.ToDataSourceResult(request, ModelState));
        }
    }
}

eLConsultation/Controllers/RegionController.cs
using eLConsultation.Data;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

using System.Linq;

using System.Web.Mvc;


namespace eLConsultation.Controllers
{
    [Authorize(Roles = "administrator")]
    public class RegionController : Controller
    {
        RegionService service;

        public RegionController()
        {
            service = new RegionService();
        }

        public JsonResult RegionList()
        {
            return Json(service.GetRegions(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RegionSelect([DataSourceRequest] DataSourceRequest request)
        {
            return Json(service.GetRegions().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult RegionCreate([DataSourceRequest] DataSourceRequest request, RegionItem regionItem)
        {
            if (regionItem != null && ModelState.IsValid)
            {
                service.CreateRegion(regionItem);
            }
            return Json(new[] { regionItem }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult RegionUpdate([DataSourceRequest] DataSourceRequest request, RegionItem regionItem)
        {
            if (regionItem != null && ModelState.IsValid)
            {
                service.UpdateRegion(regionItem);
            }
            return Json(new[] { regionItem }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult RegionDelete([DataSourceRequest] DataSourceRequest request, RegionItem regionItem)
        {
            if (regionItem != null)
            {
                service.DeleteRegion(regionItem);
            }
            return Json(new[] { regionItem }.ToDataSourceResult(request, ModelState));
        }
    }
}

eLConsultation/Controllers/SettingController.cs
using eLConsultation.Data;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace eLConsultation.Controllers
{
    [Authorize(Roles = "administrator")]
    public class SettingController : Controller
    {
        [NonAction]
        private ViewResult ErrorHandler(Exception ex)
        {
            return View("Error", new HandleErrorInfo(ex,
                        this.ControllerContext.RouteData.Values["controller"].ToString(),
                        this.ControllerContext.RouteData.Values["action"].ToString()));
        }

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult SmtpSetting()
        {

            var smtpSettingService = new SmtpSettingService();
            var smtpSettings = smtpSettingService.GetSmtpSetting();
            return View("SmtpSetting", smtpSettings);

        }

        [HttpPost]
        public ActionResult SaveSmtpSetting(SmtpSetting smtpSetting)
        {

            var smtpSettingService = new SmtpSettingService();
            try
            {
                smtpSettingService.SetSmtpSetting(smtpSetting);
                return View("SmtpSettingSuccessful");
            }
            catch (Exception ex)
            {
                return this.ErrorHandler(ex);
            }

        }
    }
}

eLConsultation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="~/img/favicon.png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    @Styles.Render("~/Content/kendo/2017.2.621/kendo")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/kendo")
    <script>
        $(window).on('load', function () { // makes sure the whole site is loaded 
            $('#status').fadeOut(); // will first fade out the loading animation 
            $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website. 
            $('body').delay(350).css({ 'overflow': 'visible' });
        })
    </script>

</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
    <!-- Preloader -->
    <div id="preloader">
        <div id="status"></div>
    </div>
    <header class="app-header navbar">

        <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>
        <a class="navbar-brand" href="@Url.Action("", "")">ՀՔԱՎ</a>
        <button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>
        <span class="nav-link">@ViewBag.Title</span>
        <ul class="nav navbar-nav d-md-down-none">
        </ul>
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item dropdown">
                @Html.Partial("_LoginPartial")
            </li>
        </ul>
        @*<button class="navbar-toggler aside-menu-toggler" type="button">☰</button>*@
    </header>

    <div class="app-body">
        <div class="sidebar">
            <nav class="sidebar-nav">
                <ul class="nav">
                    @*<li class="nav-title">
            Գլխավոր մենյու
        </li>*@




                    <li class="nav-title">
                        Խորհրդատվություն
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "OralConsultation")"><i class="fa fa-bullhorn"></i> Բանավոր</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "TypeConsultation")"><i class="fa fa-pencil"></i> Գրավոր</a>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Resident")"><i class="fa fa-users"></i> Քաղաքացիներ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Company")"><i class="fa fa-university"></i> Կազմակերպություն</a>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("UnderConstruction", "Home")"><i class="fa fa-bar-chart"></i> Հաշվետվություններ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("UnderConstruction", "Home")"><i class="fa fa-line-chart"></i> Վերլուծություններ</a>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-database"></i> Շտեմարաններ</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "AgeGroup")"><i class="fa fa-dot-circle-o"></i> Տարիքային խումբ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Community")"><i class="fa fa-dot-circle-o"></i> Բնակավայր</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Consultant")"><i class="fa fa-dot-circle-o"></i> Խորհրդատու</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "ConsultationResult")"><i class="fa fa-dot-circle-o"></i> Արդյունք</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "ConsultationType")"><i class="fa fa-dot-circle-o"></i> Տեսակ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "DeclarationType")"><i class="fa fa-dot-circle-o"></i> Հայտարարություն</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Gender")"><i class="fa fa-dot-circle-o"></i> Սեռ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "HumanRight")"><i class="fa fa-dot-circle-o"></i> Իրավունք</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "InvocationType")"><i class="fa fa-dot-circle-o"></i> Դիմելու ձև</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Organization")"><i class="fa fa-dot-circle-o"></i> Կառույց</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "ProcessStatus")"><i class="fa fa-dot-circle-o"></i> Ընթացք</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Region")"><i class="fa fa-dot-circle-o"></i> Մարզ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "TargetGroup")"><i class="fa fa-dot-circle-o"></i> Թիրախային խումբ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "IssueType")"><i class="fa fa-dot-circle-o"></i> Խնդրի տեսակ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "IssueCategory")"><i class="fa fa-dot-circle-o"></i> Խնդրի կատեգորիա</a>
                            </li>
                        </ul>
                    </li>
                    <li class="divider"></li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-user"></i> Կառավարում</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "User")"><i class="fa fa-dot-circle-o"></i> Գործարկողներ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("SmtpSetting", "Setting")"><i class="fa fa-dot-circle-o"></i> SMTP կարգավորում</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <!-- Main content -->
        <main class="main">
            <div class="container-fluid">
                <div class="animated fadeIn">
                        @RenderBody()
                </div>
            </div>
        </main>
    </div>
    <footer class="app-footer" style="text-align:center">
           <a href="http://hcav.am/" target="_blank" >Հելսինկյան Քաղաքացիական Ասամբլեայի Վանաձորի գրասենյակ &copy; @DateTime.Now.Year</a>
        @Html.Action("Version", "Home")
    </footer>
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/bundles/bootstrap")
    
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>

eLConsultation/Views/Shared/_LayoutNull.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="~/img/favicon.png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    @Styles.Render("~/Content/kendo/2017.2.621/kendo")
    
    @Scripts.Render("~/bundles/kendo")
    @Styles.Render("~/Content/css")
    <script>
        $(window).on('load', function () { // makes sure the whole site is loaded
            $('#status').fadeOut(); // will first fade out the loading animation
            $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
            $('body').delay(350).css({ 'overflow': 'visible' });
        })
    </script>
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
    <!-- Preloader -->
    <div id="preloader">
        <div id="status"></div>
    </div>
    <header class="app-header navbar">
        @*<button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>*@
        <a class="navbar-brand" href="@Url.Action("", "")">ՀՔԱՎ</a>
        @*<button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>*@
        @*<h4 class="nav-link">@ViewBag.Title</h4>
        <ul class="nav navbar-nav d-md-down-none"></ul>
        <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">*@
            @*<a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="d-md-down-none">admin</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <a class="dropdown-item" href="@Url.Action("Login", "Home")"><i class="fa fa-lock"></i> Login</a>
            </div>*@
        @*</li>
    </ul>*@
        @*<button class="navbar-toggler aside-menu-toggler" type="button">☰</button>*@
    </header>
    <main style="padding-top: 70px;">
        @RenderBody()
    </main>

    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>

eLConsultation/Views/Shared/_LayoutResident.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="~/img/favicon.png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    @Styles.Render("~/Content/kendo/2017.2.621/kendo")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/kendo")
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">

    <header class="app-header navbar">
        <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>
        <a class="navbar-brand" href="@Url.Action("", "")"></a>
        <button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>
        <span class="nav-link">@ViewBag.Title</span>
        <ul class="nav navbar-nav d-md-down-none">
        </ul>
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item dropdown">
               
            </li>
        </ul>
    </header>

    <div class="app-body">
        <div class="sidebar">
            <nav class="sidebar-nav">
                <ul class="nav">
                    <li class="nav-title">
                        Որոնման դաշտեր
                    </li>
                    @RenderSection("SearchField")
                </ul>
            </nav>
        </div>
        <!-- Main content -->
        <main class="main">
            <div class="container-fluid">
                <div class="animated fadeIn">
                        @RenderBody()
                </div>
            </div>
        </main>
    </div>
    <footer class="app-footer">
        &copy; @DateTime.Now.Year
        <span class="float-right">
            Powered by <a href="http://dv-solutions.com" target="_blank">DV-Solutions</a>
        </span>
    </footer>
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/bundles/bootstrap")
    
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>